var data = [
{"lastName":"Demres", "firstName":"David","Age":25,"Sex":"M","Pace":5.08,"finishTime":15.56},
{"lastName":"Dextradeur", "firstName":"Thomas","Age":21,"Sex":"M","Pace":5.13,"finishTime":16.12},
{"lastName":"Wang", "firstName":"Michael","Age":18,"Sex":"M","Pace":5.14,"finishTime":16.14},
{"lastName":"Loftis", "firstName":"Cory","Age":24,"Sex":"M","Pace":5.15,"finishTime":16.17},
{"lastName":"Chaston", "firstName":"Matt","Age":47,"Sex":"M","Pace":5.27,"finishTime":16.54},
{"lastName":"Wasiolek", "firstName":"Bart","Age":46,"Sex":"M","Pace":5.27,"finishTime":16.56},
{"lastName":"Tanner", "firstName":"Morgan","Age":34,"Sex":"M","Pace":5.40,"finishTime":17.35},
{"lastName":"Smith", "firstName":"Kevin","Age":39,"Sex":"M","Pace":5.41,"finishTime":17.39},
{"lastName":"Laske", "firstName":"Patrick","Age":18,"Sex":"M","Pace":5.58,"finishTime":18.31},
{"lastName":"Jennings", "firstName":"Colby","Age":21,"Sex":"M","Pace":6.03,"finishTime":18.47},
{"lastName":"Tolbert", "firstName":"Juan","Age":54,"Sex":"M","Pace":6.04,"finishTime":18.51},
{"lastName":"Fischer", "firstName":"Eric","Age":20,"Sex":"M","Pace":6.07,"finishTime":18.59},
{"lastName":"Mariotti", "firstName":"Jackson","Age":18,"Sex":"M","Pace":6.08,"finishTime":19.04},
{"lastName":"MacDougall", "firstName":"Alan","Age":49,"Sex":"M","Pace":6.10,"finishTime":19.08},
{"lastName":"Song", "firstName":"Mike","Age":50,"Sex":"M","Pace":6.21,"finishTime":19.43},
{"lastName":"Stonier", "firstName":"Christopher","Age":30,"Sex":"M","Pace":6.25,"finishTime":19.55},
{"lastName":"Hammond", "firstName":"Sarah","Age":19,"Sex":"F","Pace":6.26,"finishTime":19.58},
{"lastName":"Goddrich", "firstName":"Dave","Age":35,"Sex":"M","Pace":6.33,"finishTime":20.2},
{"lastName":"Lionetti", "firstName":"Robbie","Age":13,"Sex":"M","Pace":6.35,"finishTime":20.25},
{"lastName":"Hernandez", "firstName":"Richard","Age":17,"Sex":"M","Pace":6.36,"finishTime":20.28},
{"lastName":"Vescovi", "firstName":"Ed","Age":52,"Sex":"M","Pace":6.39,"finishTime":20.37},
{"lastName":"Regan-Mochrie", "firstName":"James","Age":19,"Sex":"M","Pace":6.40,"finishTime":20.41},
{"lastName":"Mariotti", "firstName":"Spencer","Age":16,"Sex":"M","Pace":6.40,"finishTime":20.42},
{"lastName":"Byrne", "firstName":"Andrew","Age":15,"Sex":"M","Pace":6.41,"finishTime":20.44},
{"lastName":"McComb", "firstName":"Ryan","Age":19,"Sex":"M","Pace":6.41,"finishTime":20.45},
{"lastName":"Panciera", "firstName":"Benjamin","Age":44,"Sex":"M","Pace":6.41,"finishTime":20.46},
{"lastName":"Muniz", "firstName":"Alex","Age":19,"Sex":"M","Pace":6.43,"finishTime":20.51},
{"lastName":"Steinrueche", "firstName":"Marias","Age":25,"Sex":"M","Pace":6.46,"finishTime":21},
{"lastName":"McKee", "firstName":"Michael","Age":45,"Sex":"M","Pace":6.47,"finishTime":21.02},
{"lastName":"Pakuta", "firstName":"Christine","Age":33,"Sex":"F","Pace":6.47,"finishTime":21.03},
{"lastName":"Opie", "firstName":"Tanner","Age":16,"Sex":"M","Pace":6.50,"finishTime":21.13},
{"lastName":"Gilhuly", "firstName":"Patrick","Age":22,"Sex":"M","Pace":6.51,"finishTime":21.16},
{"lastName":"Kelly", "firstName":"Joseph","Age":34,"Sex":"M","Pace":6.52,"finishTime":21.19},
{"lastName":"Kelleher", "firstName":"Kimberley","Age":44,"Sex":"F","Pace":6.52,"finishTime":21.2},
{"lastName":"Kramer", "firstName":"Kyle","Age":25,"Sex":"M","Pace":6.55,"finishTime":21.29},
{"lastName":"Thetonia", "firstName":"Kyle","Age":32,"Sex":"M","Pace":6.56,"finishTime":21.31},
{"lastName":"Wang", "firstName":"Helen","Age":22,"Sex":"F","Pace":6.58,"finishTime":21.37},
{"lastName":"Wasiolek", "firstName":"Anna","Age":41,"Sex":"F","Pace":7.03,"finishTime":21.54},
{"lastName":"Antonioni", "firstName":"Michangelo","Age":42,"Sex":"M","Pace":7.07,"finishTime":22.05},
{"lastName":"Cramer", "firstName":"Lukas","Age":25,"Sex":"M","Pace":7.07,"finishTime":22.07},
{"lastName":"Mason", "firstName":"Rick","Age":44,"Sex":"M","Pace":7.08,"finishTime":22.09},
{"lastName":"Dauenhauer", "firstName":"Mike","Age":27,"Sex":"M","Pace":7.08,"finishTime":22.1},
{"lastName":"Weaver", "firstName":"Warren","Age":42,"Sex":"M","Pace":7.09,"finishTime":22.13},
{"lastName":"Phillips", "firstName":"Tesni","Age":19,"Sex":"F","Pace":7.10,"finishTime":22.13},
{"lastName":"Curl", "firstName":"Christopher","Age":44,"Sex":"M","Pace":7.10,"finishTime":22.13},
{"lastName":"O'Brien", "firstName":"Michael","Age":26,"Sex":"M","Pace":7.10,"finishTime":22.14},
{"lastName":"Song", "firstName":"Evan","Age":15,"Sex":"M","Pace":7.10,"finishTime":22.14},
{"lastName":"Linder", "firstName":"Billy","Age":11,"Sex":"M","Pace":7.16,"finishTime":22.33},
{"lastName":"Sidney", "firstName":"Lawrence","Age":42,"Sex":"M","Pace":7.16,"finishTime":22.35},
{"lastName":"Manderson", "firstName":"Kerstin","Age":33,"Sex":"F","Pace":7.16,"finishTime":22.35},
{"lastName":"Hynes", "firstName":"Brennan","Age":11,"Sex":"M","Pace":7.17,"finishTime":22.38},
{"lastName":"Opie", "firstName":"John","Age":18,"Sex":"M","Pace":7.19,"finishTime":22.44},
{"lastName":"Vitale", "firstName":"Robert","Age":51,"Sex":"M","Pace":7.20,"finishTime":22.46},
{"lastName":"McKittrick", "firstName":"John-Michael","Age":37,"Sex":"M","Pace":7.20,"finishTime":22.47},
{"lastName":"Sinusas", "firstName":"Paul","Age":35,"Sex":"M","Pace":7.20,"finishTime":22.47},
{"lastName":"Osmond", "firstName":"Adam","Age":47,"Sex":"M","Pace":7.21,"finishTime":22.49},
{"lastName":"Germana", "firstName":"Nick","Age":39,"Sex":"M","Pace":7.21,"finishTime":22.5},
{"lastName":"Rivera", "firstName":"Jonathan","Age":35,"Sex":"M","Pace":7.22,"finishTime":22.53},
{"lastName":"Quinlin", "firstName":"Gary","Age":52,"Sex":"M","Pace":7.23,"finishTime":22.55},
{"lastName":"MacDougall", "firstName":"Margit","Age":48,"Sex":"F","Pace":7.24,"finishTime":22.58},
{"lastName":"Theilgard", "firstName":"Nicholas","Age":12,"Sex":"M","Pace":7.24,"finishTime":23},
{"lastName":"Wines", "firstName":"Susan","Age":49,"Sex":"F","Pace":7.25,"finishTime":23.01},
{"lastName":"Evans", "firstName":"Richard","Age":42,"Sex":"M","Pace":7.27,"finishTime":23.08},
{"lastName":"Newlan", "firstName":"Christopher","Age":42,"Sex":"M","Pace":7.28,"finishTime":23.1},
{"lastName":"Young", "firstName":"Ryan","Age":19,"Sex":"M","Pace":7.28,"finishTime":23.12},
{"lastName":"Spera", "firstName":"Maleana","Age":33,"Sex":"F","Pace":7.31,"finishTime":23.2},
{"lastName":"Caruso", "firstName":"Josh","Age":38,"Sex":"M","Pace":7.32,"finishTime":23.23},
{"lastName":"Harper", "firstName":"Sharon","Age":33,"Sex":"F","Pace":7.32,"finishTime":23.24},
{"lastName":"Pepe", "firstName":"Matthew","Age":31,"Sex":"M","Pace":7.33,"finishTime":23.26},
{"lastName":"Ziemba", "firstName":"Tom","Age":49,"Sex":"M","Pace":7.33,"finishTime":23.27},
{"lastName":"Verillo", "firstName":"Tom","Age":32,"Sex":"M","Pace":7.34,"finishTime":23.28},
{"lastName":"Bowman", "firstName":"Nora","Age":31,"Sex":"F","Pace":7.34,"finishTime":23.29},
{"lastName":"Simmons", "firstName":"April","Age":18,"Sex":"F","Pace":7.34,"finishTime":23.29},
{"lastName":"Visnic", "firstName":"Colleen","Age":15,"Sex":"F","Pace":7.34,"finishTime":23.3},
{"lastName":"Pearce", "firstName":"Barbara","Age":60,"Sex":"F","Pace":7.34,"finishTime":23.3},
{"lastName":"Bysiewicz", "firstName":"Sophie","Age":18,"Sex":"F","Pace":7.35,"finishTime":23.32},
{"lastName":"Medeiros", "firstName":"Joe","Age":53,"Sex":"M","Pace":7.35,"finishTime":23.33},
{"lastName":"Walden", "firstName":"Shane","Age":38,"Sex":"M","Pace":7.36,"finishTime":23.35},
{"lastName":"Kelleher", "firstName":"John","Age":10,"Sex":"M","Pace":7.37,"finishTime":23.38},
{"lastName":"Woodward", "firstName":"Tyler","Age":13,"Sex":"M","Pace":7.37,"finishTime":23.38},
{"lastName":"Calter", "firstName":"Michael","Age":48,"Sex":"M","Pace":7.37,"finishTime":23.4},
{"lastName":"D'Addetta", "firstName":"Michael","Age":57,"Sex":"M","Pace":7.38,"finishTime":23.42},
{"lastName":"Rubsam", "firstName":"John","Age":28,"Sex":"M","Pace":7.38,"finishTime":23.43},
{"lastName":"Panciera", "firstName":"Aaron","Age":17,"Sex":"M","Pace":7.39,"finishTime":23.45},
{"lastName":"Audet", "firstName":"Marc","Age":55,"Sex":"M","Pace":7.43,"finishTime":23.57},
{"lastName":"Standish", "firstName":"Emilee","Age":20,"Sex":"F","Pace":7.43,"finishTime":23.58},
{"lastName":"Cunningham", "firstName":"Brian","Age":22,"Sex":"M","Pace":7.44,"finishTime":23.59},
{"lastName":"Phillips", "firstName":"Geraint","Age":48,"Sex":"M","Pace":7.44,"finishTime":24.02},
{"lastName":"Votto", "firstName":"Stacywn","Age":35,"Sex":"F","Pace":7.46,"finishTime":24.06},
{"lastName":"Ferguson", "firstName":"Charlie","Age":10,"Sex":"M","Pace":7.47,"finishTime":24.1},
{"lastName":"Simons", "firstName":"Rich","Age":52,"Sex":"M","Pace":7.47,"finishTime":24.11},
{"lastName":"Simmons", "firstName":"Kendall","Age":16,"Sex":"F","Pace":7.48,"finishTime":24.13},
{"lastName":"Riggs", "firstName":"William","Age":13,"Sex":"M","Pace":7.48,"finishTime":24.14},
{"lastName":"Perry", "firstName":"Catherine","Age":50,"Sex":"F","Pace":7.49,"finishTime":24.16},
{"lastName":"Pacileo", "firstName":"Christian","Age":31,"Sex":"M","Pace":7.50,"finishTime":24.18},
{"lastName":"Merola", "firstName":"Justin","Age":32,"Sex":"M","Pace":7.51,"finishTime":24.23},
{"lastName":"Ricciardelli", "firstName":"Aidan","Age":13,"Sex":"M","Pace":7.51,"finishTime":24.23},
{"lastName":"Robertson", "firstName":"Tyler","Age":14,"Sex":"M","Pace":7.52,"finishTime":24.24},
{"lastName":"Whelen", "firstName":"Leah","Age":29,"Sex":"F","Pace":7.53,"finishTime":24.28},
{"lastName":"Bellonso", "firstName":"Jon","Age":30,"Sex":"M","Pace":7.53,"finishTime":24.28},
{"lastName":"Febbraio", "firstName":"Karen","Age":61,"Sex":"F","Pace":7.53,"finishTime":24.29},
{"lastName":"Perez", "firstName":"Roger","Age":48,"Sex":"M","Pace":7.55,"finishTime":24.34},
{"lastName":"Reagle", "firstName":"Charles","Age":52,"Sex":"M","Pace":7.55,"finishTime":24.35},
{"lastName":"Benzi", "firstName":"Grace","Age":12,"Sex":"F","Pace":7.56,"finishTime":24.39},
{"lastName":"Kelleher", "firstName":"Lydia","Age":13,"Sex":"F","Pace":7.58,"finishTime":24.43},
{"lastName":"Goodwin", "firstName":"Chris","Age":32,"Sex":"M","Pace":7.58,"finishTime":24.44},
{"lastName":"Glass", "firstName":"Jennifer","Age":49,"Sex":"F","Pace":7.59,"finishTime":24.46},
{"lastName":"Gore-Grimes", "firstName":"Colin","Age":11,"Sex":"M","Pace":7.59,"finishTime":24.47},
{"lastName":"Acquarulo", "firstName":"Justin","Age":11,"Sex":"M","Pace":8.01,"finishTime":24.52},
{"lastName":"Lionetti", "firstName":"Isla","Age":11,"Sex":"F","Pace":8.01,"finishTime":24.54},
{"lastName":"Braun", "firstName":"Zach","Age":16,"Sex":"M","Pace":8.01,"finishTime":24.55},
{"lastName":"Revenaugh", "firstName":"Berkeley","Age":44,"Sex":"F","Pace":8.02,"finishTime":24.57},
{"lastName":"Cosgrove", "firstName":"Meaghan","Age":34,"Sex":"F","Pace":8.02,"finishTime":24.58},
{"lastName":"Fumiatti", "firstName":"Michael","Age":27,"Sex":"M","Pace":8.03,"finishTime":24.59},
{"lastName":"Rosivach", "firstName":"Andrew","Age":40,"Sex":"M","Pace":8.03,"finishTime":25},
{"lastName":"Angelo", "firstName":"Sophia","Age":16,"Sex":"F","Pace":8.03,"finishTime":25},
{"lastName":"Spencer", "firstName":"Sophie","Age":14,"Sex":"F","Pace":8.04,"finishTime":25.01},
{"lastName":"Vitale", "firstName":"Madeline","Age":16,"Sex":"F","Pace":8.04,"finishTime":25.02},
{"lastName":"Boland", "firstName":"Ann","Age":54,"Sex":"F","Pace":8.04,"finishTime":25.04},
{"lastName":"Ross", "firstName":"Emily","Age":13,"Sex":"F","Pace":8.05,"finishTime":25.06},
{"lastName":"Joyce", "firstName":"Matthew","Age":33,"Sex":"M","Pace":8.06,"finishTime":25.09},
{"lastName":"Joyce", "firstName":"David","Age":36,"Sex":"M","Pace":8.06,"finishTime":25.09},
{"lastName":"Reardon", "firstName":"Conor","Age":28,"Sex":"M","Pace":8.07,"finishTime":25.12},
{"lastName":"Howe", "firstName":"Gregory","Age":50,"Sex":"M","Pace":8.07,"finishTime":25.12},
{"lastName":"Rooney", "firstName":"Leigh","Age":20,"Sex":"F","Pace":8.07,"finishTime":25.13},
{"lastName":"Galli", "firstName":"Luis","Age":37,"Sex":"M","Pace":8.08,"finishTime":25.14},
{"lastName":"Ardito", "firstName":"Alisa","Age":27,"Sex":"F","Pace":8.08,"finishTime":25.14},
{"lastName":"Reardon", "firstName":"Brendan","Age":23,"Sex":"M","Pace":8.08,"finishTime":25.16},
{"lastName":"Passarello", "firstName":"Anthony","Age":45,"Sex":"M","Pace":8.08,"finishTime":25.16},
{"lastName":"Rooney", "firstName":"Tracy","Age":54,"Sex":"F","Pace":8.09,"finishTime":25.17},
{"lastName":"Shaw", "firstName":"Suzanne","Age":40,"Sex":"F","Pace":8.09,"finishTime":25.18},
{"lastName":"Sulkowski", "firstName":"Stephanie","Age":21,"Sex":"F","Pace":8.09,"finishTime":25.19},
{"lastName":"Walsh", "firstName":"Margaret","Age":23,"Sex":"F","Pace":8.09,"finishTime":25.19},
{"lastName":"Haile", "firstName":"Jackson","Age":14,"Sex":"M","Pace":8.10,"finishTime":25.22},
{"lastName":"Simmons", "firstName":"Kevin","Age":50,"Sex":"M","Pace":8.12,"finishTime":25.26},
{"lastName":"Brainerd", "firstName":"Kyle","Age":10,"Sex":"M","Pace":8.12,"finishTime":25.29},
{"lastName":"Brainerd", "firstName":"Kevin","Age":42,"Sex":"M","Pace":8.13,"finishTime":25.3},
{"lastName":"Ferraro", "firstName":"Tara","Age":31,"Sex":"F","Pace":8.14,"finishTime":25.33},
{"lastName":"Bowman", "firstName":"Kerry","Age":27,"Sex":"F","Pace":8.14,"finishTime":25.33},
{"lastName":"Tomak", "firstName":"Patrick","Age":48,"Sex":"M","Pace":8.15,"finishTime":25.36},
{"lastName":"Inchalik", "firstName":"Sam","Age":15,"Sex":"M","Pace":8.17,"finishTime":25.42},
{"lastName":"Bysiewicz", "firstName":"Isabel","Age":16,"Sex":"F","Pace":8.18,"finishTime":25.46},
{"lastName":"Leonzo", "firstName":"Bob","Age":27,"Sex":"M","Pace":8.18,"finishTime":25.46},
{"lastName":"Bjork", "firstName":"Ken","Age":46,"Sex":"M","Pace":8.18,"finishTime":25.47},
{"lastName":"Andres", "firstName":"Charles","Age":59,"Sex":"M","Pace":8.18,"finishTime":25.47},
{"lastName":"Downey", "firstName":"John","Age":23,"Sex":"M","Pace":8.19,"finishTime":25.51},
{"lastName":"Ghilardi", "firstName":"Kenneth","Age":59,"Sex":"M","Pace":8.20,"finishTime":25.53},
{"lastName":"Lemay", "firstName":"Tracey","Age":38,"Sex":"F","Pace":8.21,"finishTime":25.55},
{"lastName":"Evans", "firstName":"Spencer","Age":21,"Sex":"M","Pace":8.22,"finishTime":25.58},
{"lastName":"Howlett", "firstName":"Jackie","Age":13,"Sex":"F","Pace":8.22,"finishTime":25.59},
{"lastName":"Paye", "firstName":"Brittney","Age":28,"Sex":"F","Pace":8.23,"finishTime":26.01},
{"lastName":"Johnson", "firstName":"Max","Age":12,"Sex":"M","Pace":8.24,"finishTime":26.05},
{"lastName":"Bysiewicz", "firstName":"Raissi","Age":16,"Sex":"F","Pace":8.24,"finishTime":26.05},
{"lastName":"Ricciardelli", "firstName":"Ralph","Age":53,"Sex":"M","Pace":8.26,"finishTime":26.12},
{"lastName":"Lalonde", "firstName":"Keegan","Age":10,"Sex":"M","Pace":8.27,"finishTime":26.13},
{"lastName":"Theilgard", "firstName":"Michelle","Age":15,"Sex":"F","Pace":8.27,"finishTime":26.13},
{"lastName":"Herbert", "firstName":"Tara","Age":45,"Sex":"F","Pace":8.27,"finishTime":26.14},
{"lastName":"Kiely", "firstName":"Patricia","Age":46,"Sex":"F","Pace":8.27,"finishTime":26.15},
{"lastName":"Bjork", "firstName":"Christian","Age":12,"Sex":"M","Pace":8.28,"finishTime":26.17},
{"lastName":"Geballe", "firstName":"Will","Age":10,"Sex":"M","Pace":8.28,"finishTime":26.18},
{"lastName":"Edwards", "firstName":"Heather","Age":38,"Sex":"F","Pace":8.29,"finishTime":26.19},
{"lastName":"Ferguson", "firstName":"Niall","Age":40,"Sex":"M","Pace":8.29,"finishTime":26.2},
{"lastName":"Lecza", "firstName":"Sandy","Age":46,"Sex":"M","Pace":8.30,"finishTime":26.23},
{"lastName":"Raynor", "firstName":"Lindsey","Age":23,"Sex":"F","Pace":8.30,"finishTime":26.24},
{"lastName":"Platz", "firstName":"Ken","Age":67,"Sex":"M","Pace":8.31,"finishTime":26.26},
{"lastName":"Janosko", "firstName":"Jeffrey","Age":40,"Sex":"M","Pace":8.31,"finishTime":26.27},
{"lastName":"Holzer", "firstName":"Trevor","Age":11,"Sex":"M","Pace":8.31,"finishTime":26.27},
{"lastName":"Ghilardi", "firstName":"Barbara","Age":27,"Sex":"F","Pace":8.31,"finishTime":26.28},
{"lastName":"Castagna", "firstName":"Sabrina","Age":50,"Sex":"F","Pace":8.33,"finishTime":26.31},
{"lastName":"Brown", "firstName":"Jeffery","Age":52,"Sex":"M","Pace":8.35,"finishTime":26.4},
{"lastName":"Fedorowich", "firstName":"Talia","Age":36,"Sex":"F","Pace":8.36,"finishTime":26.43},
{"lastName":"Cunningham", "firstName":"Collin","Age":27,"Sex":"M","Pace":8.38,"finishTime":26.47},
{"lastName":"Chiin", "firstName":"Hyiing","Age":40,"Sex":"M","Pace":8.38,"finishTime":26.48},
{"lastName":"King", "firstName":"Sue","Age":13,"Sex":"F","Pace":8.38,"finishTime":26.49},
{"lastName":"Goregrimes", "firstName":"Simon","Age":47,"Sex":"M","Pace":8.38,"finishTime":26.49},
{"lastName":"McMullen", "firstName":"Alexandra","Age":35,"Sex":"F","Pace":8.38,"finishTime":26.5},
{"lastName":"Mollow", "firstName":"William","Age":10,"Sex":"M","Pace":8.39,"finishTime":26.51},
{"lastName":"Boland", "firstName":"Ingrid","Age":14,"Sex":"F","Pace":8.39,"finishTime":26.52},
{"lastName":"Hanson", "firstName":"Gunnar","Age":13,"Sex":"M","Pace":8.39,"finishTime":26.53},
{"lastName":"Bedoya", "firstName":"Jose","Age":47,"Sex":"M","Pace":8.41,"finishTime":26.57},
{"lastName":"Kelleher", "firstName":"Erin","Age":11,"Sex":"F","Pace":8.41,"finishTime":26.58},
{"lastName":"Nevius", "firstName":"Erin","Age":33,"Sex":"F","Pace":8.41,"finishTime":26.58},
{"lastName":"Wells", "firstName":"Ryan","Age":30,"Sex":"M","Pace":8.41,"finishTime":26.59},
{"lastName":"Wells", "firstName":"Kristin","Age":30,"Sex":"F","Pace":8.41,"finishTime":26.59},
{"lastName":"Backhaus", "firstName":"Olivia","Age":18,"Sex":"F","Pace":8.42,"finishTime":27.02},
{"lastName":"Pulino", "firstName":"Guy","Age":69,"Sex":"M","Pace":8.43,"finishTime":27.03},
{"lastName":"Backhaus", "firstName":"Robert","Age":47,"Sex":"M","Pace":8.43,"finishTime":27.04},
{"lastName":"Jacobson", "firstName":"Carl","Age":13,"Sex":"M","Pace":8.43,"finishTime":27.04},
{"lastName":"O'Brien", "firstName":"Margaret","Age":53,"Sex":"F","Pace":8.43,"finishTime":27.05},
{"lastName":"Suter", "firstName":"Fenn","Age":13,"Sex":"M","Pace":8.44,"finishTime":27.08},
{"lastName":"Beers", "firstName":"Theodore","Age":27,"Sex":"M","Pace":8.46,"finishTime":27.13},
{"lastName":"Ghio", "firstName":"Bill","Age":60,"Sex":"M","Pace":8.47,"finishTime":27.16},
{"lastName":"Baseggio", "firstName":"David","Age":47,"Sex":"M","Pace":8.48,"finishTime":27.18},
{"lastName":"Gerzabek", "firstName":"Jill","Age":25,"Sex":"F","Pace":8.48,"finishTime":27.19},
{"lastName":"Demusis", "firstName":"Emily","Age":30,"Sex":"F","Pace":8.49,"finishTime":27.24},
{"lastName":"Demusis", "firstName":"Abigail","Age":26,"Sex":"F","Pace":8.49,"finishTime":27.24},
{"lastName":"Page", "firstName":"Brian","Age":9,"Sex":"M","Pace":8.49,"finishTime":27.24},
{"lastName":"Ortega", "firstName":"Josue","Age":9,"Sex":"M","Pace":8.50,"finishTime":27.26},
{"lastName":"Gordon", "firstName":"Erin","Age":30,"Sex":"F","Pace":8.50,"finishTime":27.26},
{"lastName":"Linder", "firstName":"Jack","Age":9,"Sex":"M","Pace":8.51,"finishTime":27.28},
{"lastName":"Dionne", "firstName":"Christina","Age":33,"Sex":"F","Pace":8.52,"finishTime":27.3},
{"lastName":"Zeidenberg", "firstName":"Todd","Age":53,"Sex":"M","Pace":8.52,"finishTime":27.32},
{"lastName":"Anderson", "firstName":"Angela","Age":55,"Sex":"F","Pace":8.53,"finishTime":27.34},
{"lastName":"Hodge", "firstName":"Michael","Age":39,"Sex":"M","Pace":8.53,"finishTime":27.35},
{"lastName":"Zeranski", "firstName":"Mike","Age":36,"Sex":"M","Pace":8.53,"finishTime":27.36},
{"lastName":"Bonanno", "firstName":"Dominic","Age":11,"Sex":"M","Pace":8.54,"finishTime":27.38},
{"lastName":"Stevenson", "firstName":"Margaret","Age":25,"Sex":"F","Pace":8.54,"finishTime":27.38},
{"lastName":"Spaulding", "firstName":"Caroline","Age":10,"Sex":"F","Pace":8.54,"finishTime":27.39},
{"lastName":"Kuehl", "firstName":"Margaret","Age":17,"Sex":"F","Pace":8.55,"finishTime":27.4},
{"lastName":"Defilio", "firstName":"Anthony","Age":10,"Sex":"M","Pace":8.55,"finishTime":27.4},
{"lastName":"Linder", "firstName":"Megan","Age":47,"Sex":"F","Pace":8.55,"finishTime":27.42},
{"lastName":"Rowe", "firstName":"Madeline","Age":15,"Sex":"F","Pace":8.56,"finishTime":27.43},
{"lastName":"Sharkey", "firstName":"Melinda","Age":38,"Sex":"F","Pace":8.56,"finishTime":27.44},
{"lastName":"Johnson", "firstName":"Leslie","Age":57,"Sex":"F","Pace":8.56,"finishTime":27.45},
{"lastName":"Hanson", "firstName":"Eric","Age":49,"Sex":"M","Pace":8.57,"finishTime":27.46},
{"lastName":"Copenhaver", "firstName":"Michael","Age":50,"Sex":"M","Pace":8.57,"finishTime":27.47},
{"lastName":"Dalton", "firstName":"Timothy","Age":39,"Sex":"M","Pace":8.58,"finishTime":27.5},
{"lastName":"Goclowski", "firstName":"Bob","Age":57,"Sex":"M","Pace":8.59,"finishTime":27.52},
{"lastName":"Ferguson", "firstName":"Elizabeth","Age":39,"Sex":"F","Pace":8.59,"finishTime":27.54},
{"lastName":"Gatta", "firstName":"Michael","Age":43,"Sex":"M","Pace":8.59,"finishTime":27.54},
{"lastName":"Sharkey", "firstName":"Sue","Age":64,"Sex":"F","Pace":9.01,"finishTime":28.01},
{"lastName":"Crozier", "firstName":"Wesley","Age":29,"Sex":"M","Pace":9.02,"finishTime":28.02},
{"lastName":"O'Neil", "firstName":"Paul","Age":14,"Sex":"M","Pace":9.02,"finishTime":28.03},
{"lastName":"Ball", "firstName":"Joseph","Age":36,"Sex":"M","Pace":9.02,"finishTime":28.04},
{"lastName":"McMahon", "firstName":"Sarah","Age":26,"Sex":"F","Pace":9.03,"finishTime":28.05},
{"lastName":"McMahon", "firstName":"Gregory","Age":54,"Sex":"M","Pace":9.03,"finishTime":28.06},
{"lastName":"Baseggio", "firstName":"Michael","Age":13,"Sex":"M","Pace":9.03,"finishTime":28.06},
{"lastName":"Thompson", "firstName":"Andrei","Age":13,"Sex":"M","Pace":9.03,"finishTime":28.06},
{"lastName":"Suydam", "firstName":"Trevor","Age":15,"Sex":"M","Pace":9.03,"finishTime":28.07},
{"lastName":"Sutcliffe", "firstName":"Jamie","Age":20,"Sex":"F","Pace":9.03,"finishTime":28.07},
{"lastName":"Pakuta", "firstName":"John","Age":50,"Sex":"M","Pace":9.04,"finishTime":28.09},
{"lastName":"Swift", "firstName":"Katherine","Age":42,"Sex":"F","Pace":9.04,"finishTime":28.1},
{"lastName":"Pierson", "firstName":"Rj","Age":18,"Sex":"M","Pace":9.04,"finishTime":28.1},
{"lastName":"Shaw", "firstName":"Jolene","Age":36,"Sex":"F","Pace":9.05,"finishTime":28.12},
{"lastName":"Barrett", "firstName":"Janet","Age":55,"Sex":"F","Pace":9.06,"finishTime":28.14},
{"lastName":"Barrett", "firstName":"Margaret","Age":31,"Sex":"F","Pace":9.06,"finishTime":28.15},
{"lastName":"Picar", "firstName":"Amy","Age":38,"Sex":"F","Pace":9.06,"finishTime":28.16},
{"lastName":"Smith", "firstName":"Daniel","Age":29,"Sex":"M","Pace":9.06,"finishTime":28.16},
{"lastName":"Nichols", "firstName":"Grayson","Age":7,"Sex":"M","Pace":9.06,"finishTime":28.17},
{"lastName":"Kaiser", "firstName":"David","Age":60,"Sex":"M","Pace":9.07,"finishTime":28.17},
{"lastName":"Gilhuly", "firstName":"Caitlin","Age":23,"Sex":"F","Pace":9.07,"finishTime":28.18},
{"lastName":"Idelson", "firstName":"Douglas","Age":44,"Sex":"M","Pace":9.07,"finishTime":28.18},
{"lastName":"Rogers", "firstName":"Lucy","Age":33,"Sex":"F","Pace":9.07,"finishTime":28.2},
{"lastName":"Ncnamara", "firstName":"Erica","Age":30,"Sex":"F","Pace":9.08,"finishTime":28.22},
{"lastName":"Reeve", "firstName":"Bronwyn","Age":18,"Sex":"F","Pace":9.08,"finishTime":28.23},
{"lastName":"Kelleher", "firstName":"Ed","Age":48,"Sex":"M","Pace":9.09,"finishTime":28.23},
{"lastName":"Gilhuly", "firstName":"Mark","Age":59,"Sex":"M","Pace":9.09,"finishTime":28.23},
{"lastName":"Stevens", "firstName":"Jacob","Age":36,"Sex":"M","Pace":9.09,"finishTime":28.24},
{"lastName":"Cunningham", "firstName":"Paige","Age":26,"Sex":"F","Pace":9.10,"finishTime":28.28},
{"lastName":"Razza", "firstName":"Renata","Age":42,"Sex":"F","Pace":9.12,"finishTime":28.33},
{"lastName":"Guglielmo", "firstName":"August","Age":13,"Sex":"M","Pace":9.12,"finishTime":28.34},
{"lastName":"Brinius", "firstName":"George","Age":39,"Sex":"M","Pace":9.12,"finishTime":28.35},
{"lastName":"Guglielmo", "firstName":"Paul","Age":59,"Sex":"M","Pace":9.13,"finishTime":28.36},
{"lastName":"Silver", "firstName":"Lora","Age":30,"Sex":"F","Pace":9.13,"finishTime":28.37},
{"lastName":"Harkins", "firstName":"Michael","Age":52,"Sex":"M","Pace":9.14,"finishTime":28.39},
{"lastName":"Mason", "firstName":"Jeffrey","Age":35,"Sex":"M","Pace":9.14,"finishTime":28.39},
{"lastName":"Hammond", "firstName":"Julia","Age":16,"Sex":"F","Pace":9.14,"finishTime":28.39},
{"lastName":"Pair", "firstName":"Ray","Age":72,"Sex":"M","Pace":9.14,"finishTime":28.4},
{"lastName":"Zeidenberg", "firstName":"Toby","Age":10,"Sex":"M","Pace":9.14,"finishTime":28.41},
{"lastName":"Piselli", "firstName":"Caroline","Age":27,"Sex":"F","Pace":9.15,"finishTime":28.42},
{"lastName":"Piselli", "firstName":"Jennifer","Age":22,"Sex":"F","Pace":9.15,"finishTime":28.43},
{"lastName":"Fedorchak", "firstName":"Phil","Age":49,"Sex":"M","Pace":9.15,"finishTime":28.43},
{"lastName":"Wille", "firstName":"Cecilia","Age":24,"Sex":"F","Pace":9.15,"finishTime":28.44},
{"lastName":"Rauccio", "firstName":"Genna","Age":11,"Sex":"F","Pace":9.16,"finishTime":28.45},
{"lastName":"Savinelli", "firstName":"Tony","Age":59,"Sex":"M","Pace":9.16,"finishTime":28.46},
{"lastName":"Wille", "firstName":"Lowell","Age":59,"Sex":"M","Pace":9.16,"finishTime":28.47},
{"lastName":"Pellegrino", "firstName":"Anissa","Age":44,"Sex":"F","Pace":9.17,"finishTime":28.49},
{"lastName":"Muniz", "firstName":"Paul","Age":54,"Sex":"M","Pace":9.17,"finishTime":28.49},
{"lastName":"Gangemi", "firstName":"Tony","Age":46,"Sex":"M","Pace":9.17,"finishTime":28.5},
{"lastName":"D'Amuri", "firstName":"Francesco","Age":40,"Sex":"M","Pace":9.18,"finishTime":28.51},
{"lastName":"Park", "firstName":"Regina","Age":31,"Sex":"F","Pace":9.18,"finishTime":28.52},
{"lastName":"Chang", "firstName":"Miyoung","Age":44,"Sex":"F","Pace":9.18,"finishTime":28.53},
{"lastName":"Cunningham", "firstName":"Richard","Age":54,"Sex":"M","Pace":9.18,"finishTime":28.53},
{"lastName":"Dwyer", "firstName":"Rick","Age":45,"Sex":"M","Pace":9.19,"finishTime":28.55},
{"lastName":"Weiss", "firstName":"Charly","Age":45,"Sex":"F","Pace":9.19,"finishTime":28.55},
{"lastName":"Geballe", "firstName":"Ali","Age":41,"Sex":"F","Pace":9.19,"finishTime":28.55},
{"lastName":"Woodward", "firstName":"Ashley","Age":12,"Sex":"F","Pace":9.19,"finishTime":28.55},
{"lastName":"Stevenson", "firstName":"Patrick","Age":28,"Sex":"M","Pace":9.19,"finishTime":28.55},
{"lastName":"Peck", "firstName":"Emily","Age":30,"Sex":"F","Pace":9.19,"finishTime":28.56},
{"lastName":"Woodward", "firstName":"Allyson","Age":9,"Sex":"F","Pace":9.19,"finishTime":28.56},
{"lastName":"Jacobson", "firstName":"Kelliwn","Age":11,"Sex":"F","Pace":9.19,"finishTime":28.56},
{"lastName":"Angkatavanide", "firstName":"Owen","Age":10,"Sex":"M","Pace":9.21,"finishTime":29.01},
{"lastName":"Young", "firstName":"Allison","Age":17,"Sex":"F","Pace":9.21,"finishTime":29.02},
{"lastName":"Defilio", "firstName":"Gina","Age":41,"Sex":"F","Pace":9.21,"finishTime":29.03},
{"lastName":"Burkle", "firstName":"Taylor","Age":13,"Sex":"F","Pace":9.22,"finishTime":29.05},
{"lastName":"Burkle", "firstName":"Nick","Age":19,"Sex":"M","Pace":9.22,"finishTime":29.05},
{"lastName":"Park", "firstName":"Daniel","Age":30,"Sex":"M","Pace":9.22,"finishTime":29.05},
{"lastName":"Lennon-Gomez", "firstName":"Gena","Age":34,"Sex":"F","Pace":9.22,"finishTime":29.06},
{"lastName":"Zambory", "firstName":"Taryn","Age":35,"Sex":"F","Pace":9.22,"finishTime":29.06},
{"lastName":"Woodward", "firstName":"Alyssa","Age":10,"Sex":"F","Pace":9.23,"finishTime":29.09},
{"lastName":"Robinson", "firstName":"Tricia","Age":46,"Sex":"F","Pace":9.23,"finishTime":29.09},
{"lastName":"Ferraro", "firstName":"Kaitlynn","Age":22,"Sex":"F","Pace":9.24,"finishTime":29.11},
{"lastName":"Ferraro", "firstName":"Paul","Age":50,"Sex":"M","Pace":9.24,"finishTime":29.11},
{"lastName":"Backer", "firstName":"Anton","Age":30,"Sex":"M","Pace":9.24,"finishTime":29.12},
{"lastName":"McCartney", "firstName":"Ann-Marie","Age":45,"Sex":"F","Pace":9.25,"finishTime":29.14},
{"lastName":"Baker", "firstName":"Charles","Age":32,"Sex":"M","Pace":9.25,"finishTime":29.14},
{"lastName":"Reardon", "firstName":"Timothy","Age":59,"Sex":"M","Pace":9.26,"finishTime":29.17},
{"lastName":"Woodward", "firstName":"Karen","Age":38,"Sex":"F","Pace":9.26,"finishTime":29.17},
{"lastName":"Sullivan", "firstName":"Bailey","Age":19,"Sex":"F","Pace":9.26,"finishTime":29.17},
{"lastName":"Sullivan", "firstName":"Stacey","Age":50,"Sex":"F","Pace":9.26,"finishTime":29.17},
{"lastName":"Pascarella", "firstName":"Clement","Age":40,"Sex":"M","Pace":9.26,"finishTime":29.17},
{"lastName":"Woodward", "firstName":"Cooper","Age":7,"Sex":"M","Pace":9.26,"finishTime":29.17},
{"lastName":"Pascarella", "firstName":"Tyler","Age":8,"Sex":"M","Pace":9.26,"finishTime":29.18},
{"lastName":"Wrede", "firstName":"Thomas","Age":25,"Sex":"M","Pace":9.26,"finishTime":29.18},
{"lastName":"Wrede", "firstName":"Jacqueline","Age":23,"Sex":"F","Pace":9.26,"finishTime":29.18},
{"lastName":"Deegan", "firstName":"Claudia","Age":18,"Sex":"F","Pace":9.26,"finishTime":29.19},
{"lastName":"Oconnor", "firstName":"Colby","Age":10,"Sex":"M","Pace":9.28,"finishTime":29.25},
{"lastName":"Hammond", "firstName":"Michael","Age":51,"Sex":"M","Pace":9.29,"finishTime":29.26},
{"lastName":"Sinusas", "firstName":"Rebecca","Age":36,"Sex":"F","Pace":9.29,"finishTime":29.27},
{"lastName":"Holme", "firstName":"Lisa","Age":52,"Sex":"F","Pace":9.29,"finishTime":29.28},
{"lastName":"Phelps", "firstName":"Kristen","Age":27,"Sex":"F","Pace":9.29,"finishTime":29.28},
{"lastName":"Baseggio", "firstName":"Kat","Age":10,"Sex":"F","Pace":9.30,"finishTime":29.29},
{"lastName":"Rowe", "firstName":"David","Age":51,"Sex":"M","Pace":9.30,"finishTime":29.31},
{"lastName":"Ametrano", "firstName":"Sam","Age":10,"Sex":"M","Pace":9.31,"finishTime":29.32},
{"lastName":"Conger", "firstName":"Betsy","Age":12,"Sex":"F","Pace":9.31,"finishTime":29.33},
{"lastName":"Miniter", "firstName":"Brian","Age":68,"Sex":"M","Pace":9.31,"finishTime":29.33},
{"lastName":"Holzer", "firstName":"Shawna","Age":42,"Sex":"F","Pace":9.32,"finishTime":29.35},
{"lastName":"Takvorian", "firstName":"Kim","Age":51,"Sex":"F","Pace":9.32,"finishTime":29.36},
{"lastName":"Ametrano", "firstName":"Lauren","Age":40,"Sex":"F","Pace":9.32,"finishTime":29.36},
{"lastName":"Korpinen", "firstName":"Jessica","Age":18,"Sex":"F","Pace":9.32,"finishTime":29.37},
{"lastName":"Pehr", "firstName":"Alison","Age":18,"Sex":"F","Pace":9.32,"finishTime":29.37},
{"lastName":"Perron", "firstName":"Andrew","Age":49,"Sex":"M","Pace":9.33,"finishTime":29.4},
{"lastName":"Perron", "firstName":"Grace","Age":13,"Sex":"F","Pace":9.33,"finishTime":29.4},
{"lastName":"O'Brien", "firstName":"Daniel","Age":21,"Sex":"M","Pace":9.33,"finishTime":29.4},
{"lastName":"Barbaro", "firstName":"Lisa","Age":36,"Sex":"F","Pace":9.33,"finishTime":29.4},
{"lastName":"Evon", "firstName":"Lexie","Age":16,"Sex":"F","Pace":9.34,"finishTime":29.42},
{"lastName":"Zeranski", "firstName":"Michael","Age":70,"Sex":"M","Pace":9.36,"finishTime":29.48},
{"lastName":"Lin", "firstName":"Catherine","Age":22,"Sex":"F","Pace":9.36,"finishTime":29.5},
{"lastName":"Ragonese", "firstName":"Matthew","Age":24,"Sex":"M","Pace":9.36,"finishTime":29.5},
{"lastName":"Vitale", "firstName":"Emily","Age":24,"Sex":"F","Pace":9.37,"finishTime":29.52},
{"lastName":"Vitale", "firstName":"Jean","Age":56,"Sex":"F","Pace":9.37,"finishTime":29.52},
{"lastName":"Johnson", "firstName":"Birgitta","Age":17,"Sex":"F","Pace":9.38,"finishTime":29.54},
{"lastName":"Salem", "firstName":"Allison","Age":31,"Sex":"F","Pace":9.38,"finishTime":29.54},
{"lastName":"Lapman", "firstName":"Elizabeth","Age":51,"Sex":"F","Pace":9.38,"finishTime":29.54},
{"lastName":"Reynolds", "firstName":"Wyatt","Age":10,"Sex":"M","Pace":9.38,"finishTime":29.55},
{"lastName":"Tomak", "firstName":"Sanda","Age":43,"Sex":"F","Pace":9.38,"finishTime":29.55},
{"lastName":"Flinter", "firstName":"Abigail","Age":34,"Sex":"F","Pace":9.38,"finishTime":29.56},
{"lastName":"Flinter", "firstName":"Paul","Age":64,"Sex":"M","Pace":9.38,"finishTime":29.56},
{"lastName":"Blake", "firstName":"Sarah","Age":44,"Sex":"F","Pace":9.40,"finishTime":30},
{"lastName":"Sobieski", "firstName":"Shannon","Age":35,"Sex":"F","Pace":9.41,"finishTime":30.04},
{"lastName":"Madonna", "firstName":"Stephanie","Age":31,"Sex":"F","Pace":9.42,"finishTime":30.07},
{"lastName":"Tomak", "firstName":"Samuel","Age":11,"Sex":"M","Pace":9.43,"finishTime":30.09},
{"lastName":"Riggs", "firstName":"Susan","Age":46,"Sex":"F","Pace":9.44,"finishTime":30.14},
{"lastName":"O'Connor", "firstName":"James","Age":46,"Sex":"M","Pace":9.45,"finishTime":30.15},
{"lastName":"Wilson", "firstName":"Susan","Age":48,"Sex":"F","Pace":9.45,"finishTime":30.17},
{"lastName":"Fedorchak", "firstName":"Matthew","Age":15,"Sex":"M","Pace":9.45,"finishTime":30.18},
{"lastName":"Sekiya", "firstName":"Masayo","Age":32,"Sex":"F","Pace":9.45,"finishTime":30.18},
{"lastName":"Young", "firstName":"Susan","Age":46,"Sex":"F","Pace":9.45,"finishTime":30.18},
{"lastName":"Raynor", "firstName":"Tim","Age":54,"Sex":"M","Pace":9.46,"finishTime":30.2},
{"lastName":"Raynor", "firstName":"Abigail","Age":19,"Sex":"F","Pace":9.46,"finishTime":30.2},
{"lastName":"Anderson", "firstName":"Sarah","Age":16,"Sex":"F","Pace":9.46,"finishTime":30.21},
{"lastName":"Yu", "firstName":"Kyung","Age":52,"Sex":"F","Pace":9.47,"finishTime":30.22},
{"lastName":"Provolo", "firstName":"Emmanuelle","Age":15,"Sex":"F","Pace":9.47,"finishTime":30.23},
{"lastName":"Provolo", "firstName":"Ava","Age":15,"Sex":"F","Pace":9.47,"finishTime":30.23},
{"lastName":"McKee", "firstName":"Emma","Age":13,"Sex":"F","Pace":9.48,"finishTime":30.26},
{"lastName":"Palumbo", "firstName":"Anthony","Age":46,"Sex":"M","Pace":9.48,"finishTime":30.26},
{"lastName":"Lionetti", "firstName":"Lee","Age":45,"Sex":"F","Pace":9.49,"finishTime":30.28},
{"lastName":"Sassi", "firstName":"Carrie","Age":46,"Sex":"F","Pace":9.49,"finishTime":30.28},
{"lastName":"Reynolds", "firstName":"Grahm","Age":10,"Sex":"M","Pace":9.49,"finishTime":30.3},
{"lastName":"Arsenault", "firstName":"Kelli","Age":32,"Sex":"F","Pace":9.50,"finishTime":30.31},
{"lastName":"Harper", "firstName":"Walter","Age":61,"Sex":"M","Pace":9.50,"finishTime":30.33},
{"lastName":"Cerrone", "firstName":"Makaila","Age":18,"Sex":"F","Pace":9.51,"finishTime":30.35},
{"lastName":"O'Neil", "firstName":"Andrea","Age":44,"Sex":"F","Pace":9.51,"finishTime":30.36},
{"lastName":"O'Neil", "firstName":"Andrew","Age":9,"Sex":"M","Pace":9.51,"finishTime":30.36},
{"lastName":"Rudden", "firstName":"John","Age":54,"Sex":"M","Pace":9.51,"finishTime":30.37},
{"lastName":"Dalton", "firstName":"Leigh","Age":34,"Sex":"F","Pace":9.53,"finishTime":30.41},
{"lastName":"Suydam", "firstName":"Leah","Age":11,"Sex":"F","Pace":9.54,"finishTime":30.44},
{"lastName":"Gambardella", "firstName":"Santino","Age":10,"Sex":"M","Pace":9.54,"finishTime":30.45},
{"lastName":"Kitz", "firstName":"Alexandra","Age":29,"Sex":"F","Pace":9.54,"finishTime":30.45},
{"lastName":"Pombo", "firstName":"Mollly","Age":9,"Sex":"F","Pace":9.55,"finishTime":30.46},
{"lastName":"Bradshaw", "firstName":"Michael","Age":51,"Sex":"M","Pace":9.55,"finishTime":30.47},
{"lastName":"Brooks", "firstName":"Calvin","Age":11,"Sex":"M","Pace":9.55,"finishTime":30.47},
{"lastName":"Gentile", "firstName":"Sophia","Age":17,"Sex":"F","Pace":9.55,"finishTime":30.49},
{"lastName":"Brooks", "firstName":"Erin","Age":43,"Sex":"F","Pace":9.56,"finishTime":30.5},
{"lastName":"Piazza", "firstName":"Ethan","Age":10,"Sex":"M","Pace":9.57,"finishTime":30.53},
{"lastName":"Brouder", "firstName":"Emily","Age":11,"Sex":"F","Pace":9.58,"finishTime":30.58},
{"lastName":"Perry", "firstName":"Megan","Age":14,"Sex":"F","Pace":9.59,"finishTime":30.59},
{"lastName":"Tavarozzi", "firstName":"Juliana","Age":18,"Sex":"F","Pace":9.59,"finishTime":30.59},
{"lastName":"McKay", "firstName":"Ken","Age":63,"Sex":"M","Pace":10.0,"finishTime":31.04},
{"lastName":"D'Andrea", "firstName":"Janis","Age":61,"Sex":"F","Pace":10.0,"finishTime":31.04},
{"lastName":"Polino", "firstName":"Chris","Age":51,"Sex":"M","Pace":10.0,"finishTime":31.04},
{"lastName":"Anderson", "firstName":"Courtney","Age":20,"Sex":"F","Pace":10.0,"finishTime":31.06},
{"lastName":"Brooks", "firstName":"Lola","Age":10,"Sex":"F","Pace":10.0,"finishTime":31.08},
{"lastName":"Brooks", "firstName":"Joshua","Age":43,"Sex":"M","Pace":10.0,"finishTime":31.08},
{"lastName":"Maher", "firstName":"Lauren","Age":21,"Sex":"F","Pace":10.0,"finishTime":31.09},
{"lastName":"Soper", "firstName":"Aidan","Age":8,"Sex":"M","Pace":10.0,"finishTime":31.09},
{"lastName":"Brooks", "firstName":"Andrea","Age":41,"Sex":"F","Pace":10.0,"finishTime":31.1},
{"lastName":"Piazza", "firstName":"Philip","Age":43,"Sex":"M","Pace":10.0,"finishTime":31.12},
{"lastName":"Jackson", "firstName":"Hannah","Age":9,"Sex":"F","Pace":10.0,"finishTime":31.13},
{"lastName":"Provolo", "firstName":"Natalia","Age":17,"Sex":"F","Pace":10.0,"finishTime":31.13},
{"lastName":"Medeiros", "firstName":"Lauren","Age":21,"Sex":"F","Pace":10.0,"finishTime":31.13},
{"lastName":"Fandel", "firstName":"Ryan","Age":22,"Sex":"F","Pace":10.0,"finishTime":31.13},
{"lastName":"Brei", "firstName":"Michelle","Age":36,"Sex":"F","Pace":10.0,"finishTime":31.17},
{"lastName":"Montanari", "firstName":"Andrea","Age":30,"Sex":"F","Pace":10.0,"finishTime":31.18},
{"lastName":"Meagher", "firstName":"Heidi","Age":27,"Sex":"F","Pace":10.0,"finishTime":31.2},
{"lastName":"Inchlik", "firstName":"Jackson","Age":16,"Sex":"M","Pace":10.0,"finishTime":31.22},
{"lastName":"Arpaia", "firstName":"Carl","Age":58,"Sex":"M","Pace":10.0,"finishTime":31.22},
{"lastName":"Gassner", "firstName":"Judy","Age":50,"Sex":"F","Pace":10.0,"finishTime":31.24},
{"lastName":"Henkel", "firstName":"James","Age":35,"Sex":"M","Pace":10.0,"finishTime":31.27},
{"lastName":"Allen", "firstName":"Lynn","Age":39,"Sex":"F","Pace":10.0,"finishTime":31.28},
{"lastName":"Vaughan", "firstName":"Stephen","Age":56,"Sex":"M","Pace":10.1,"finishTime":31.38},
{"lastName":"Aiken", "firstName":"Katrina","Age":35,"Sex":"F","Pace":10.1,"finishTime":31.38},
{"lastName":"Aiken", "firstName":"Todd","Age":39,"Sex":"M","Pace":10.1,"finishTime":31.38},
{"lastName":"Brouder", "firstName":"Mary","Age":47,"Sex":"F","Pace":10.1,"finishTime":31.39},
{"lastName":"Harper", "firstName":"Laureen","Age":29,"Sex":"F","Pace":10.1,"finishTime":31.43},
{"lastName":"Burr", "firstName":"Carrie","Age":36,"Sex":"F","Pace":10.1,"finishTime":31.46},
{"lastName":"Deegan", "firstName":"Barbara","Age":22,"Sex":"F","Pace":10.1,"finishTime":31.48},
{"lastName":"Mason", "firstName":"Maureen","Age":34,"Sex":"M","Pace":10.1,"finishTime":31.49},
{"lastName":"King", "firstName":"Karly","Age":12,"Sex":"F","Pace":10.1,"finishTime":31.59},
{"lastName":"Kiely", "firstName":"Meg","Age":46,"Sex":"F","Pace":10.1,"finishTime":32.01},
{"lastName":"Sherneski", "firstName":"Kerri-Ann","Age":43,"Sex":"F","Pace":10.1,"finishTime":32.02},
{"lastName":"Griffeth", "firstName":"Melissa","Age":30,"Sex":"F","Pace":10.2,"finishTime":32.05},
{"lastName":"Griffeth", "firstName":"Ryan","Age":32,"Sex":"M","Pace":10.2,"finishTime":32.05},
{"lastName":"Aghajanian", "firstName":"Ella","Age":10,"Sex":"F","Pace":10.2,"finishTime":32.07},
{"lastName":"Aghajanian", "firstName":"Michael","Age":54,"Sex":"M","Pace":10.2,"finishTime":32.07},
{"lastName":"Dolan", "firstName":"Lisa","Age":52,"Sex":"F","Pace":10.2,"finishTime":32.08},
{"lastName":"Palumbo", "firstName":"Gabrielle","Age":14,"Sex":"F","Pace":10.2,"finishTime":32.1},
{"lastName":"Bedford", "firstName":"Ashley","Age":27,"Sex":"F","Pace":10.2,"finishTime":32.11},
{"lastName":"Faitsch", "firstName":"Jack","Age":6,"Sex":"M","Pace":10.2,"finishTime":32.12},
{"lastName":"Gambardella", "firstName":"Kathleen","Age":48,"Sex":"F","Pace":10.2,"finishTime":32.12},
{"lastName":"Korpinen", "firstName":"Natalie","Age":14,"Sex":"F","Pace":10.2,"finishTime":32.15},
{"lastName":"Ziemba", "firstName":"Sarah","Age":13,"Sex":"F","Pace":10.2,"finishTime":32.15},
{"lastName":"Romberg", "firstName":"Christine","Age":34,"Sex":"F","Pace":10.2,"finishTime":32.18},
{"lastName":"Wines", "firstName":"Kacie","Age":10,"Sex":"F","Pace":10.2,"finishTime":32.19},
{"lastName":"Callaway", "firstName":"Shannon","Age":47,"Sex":"F","Pace":10.2,"finishTime":32.2},
{"lastName":"Canning", "firstName":"Robert","Age":20,"Sex":"M","Pace":10.2,"finishTime":32.21},
{"lastName":"Barone", "firstName":"Erika","Age":10,"Sex":"F","Pace":10.2,"finishTime":32.22},
{"lastName":"Barone", "firstName":"Erik","Age":41,"Sex":"M","Pace":10.2,"finishTime":32.22},
{"lastName":"Kramer", "firstName":"Tamara","Age":20,"Sex":"F","Pace":10.2,"finishTime":32.22},
{"lastName":"Buchanan", "firstName":"Eliza","Age":47,"Sex":"F","Pace":10.2,"finishTime":32.22},
{"lastName":"Martin", "firstName":"Chelesse","Age":44,"Sex":"F","Pace":10.2,"finishTime":32.27},
{"lastName":"Saverese", "firstName":"Lisa","Age":32,"Sex":"F","Pace":10.2,"finishTime":32.28},
{"lastName":"Suter", "firstName":"Halvor","Age":9,"Sex":"M","Pace":10.2,"finishTime":32.29},
{"lastName":"Reardon", "firstName":"Connor","Age":28,"Sex":"M","Pace":10.2,"finishTime":32.3},
{"lastName":"Amasino", "firstName":"Mia","Age":9,"Sex":"F","Pace":10.2,"finishTime":32.31},
{"lastName":"Phelps", "firstName":"Harrison","Age":29,"Sex":"M","Pace":10.2,"finishTime":32.31},
{"lastName":"Guerrero", "firstName":"Lindsey","Age":34,"Sex":"F","Pace":10.2,"finishTime":32.32},
{"lastName":"Smith", "firstName":"Madelynn","Age":10,"Sex":"F","Pace":10.2,"finishTime":32.32},
{"lastName":"Smith", "firstName":"Greg","Age":25,"Sex":"M","Pace":10.2,"finishTime":32.32},
{"lastName":"Smith", "firstName":"Jori","Age":39,"Sex":"F","Pace":10.2,"finishTime":32.32},
{"lastName":"Cunningham", "firstName":"Janice","Age":54,"Sex":"F","Pace":10.2,"finishTime":32.34},
{"lastName":"Suter", "firstName":"Lindsay","Age":50,"Sex":"M","Pace":10.2,"finishTime":32.34},
{"lastName":"Haskell", "firstName":"Karen","Age":37,"Sex":"F","Pace":10.3,"finishTime":32.35},
{"lastName":"Amasino", "firstName":"Jennifer","Age":37,"Sex":"F","Pace":10.3,"finishTime":32.38},
{"lastName":"Stegina", "firstName":"Hilary","Age":24,"Sex":"F","Pace":10.3,"finishTime":32.38},
{"lastName":"Suter", "firstName":"Lisa","Age":45,"Sex":"F","Pace":10.3,"finishTime":32.44},
{"lastName":"Henkel", "firstName":"Fallon","Age":33,"Sex":"F","Pace":10.3,"finishTime":32.46},
{"lastName":"Kropf", "firstName":"Sydney","Age":10,"Sex":"F","Pace":10.3,"finishTime":32.46},
{"lastName":"Lang", "firstName":"Sodie","Age":44,"Sex":"F","Pace":10.3,"finishTime":32.47},
{"lastName":"Fedorchak", "firstName":"Karen","Age":45,"Sex":"F","Pace":10.3,"finishTime":32.47},
{"lastName":"Gangemi", "firstName":"Nick","Age":9,"Sex":"M","Pace":10.3,"finishTime":32.53},
{"lastName":"Pearce", "firstName":"Thomas","Age":22,"Sex":"M","Pace":10.3,"finishTime":32.54},
{"lastName":"Marchetti", "firstName":"Rich","Age":22,"Sex":"M","Pace":10.3,"finishTime":32.54},
{"lastName":"Romberg", "firstName":"Neil","Age":38,"Sex":"M","Pace":10.3,"finishTime":32.59},
{"lastName":"Topher", "firstName":"Carroll","Age":39,"Sex":"M","Pace":10.3,"finishTime":32.59},
{"lastName":"Warner", "firstName":"Chris","Age":59,"Sex":"M","Pace":10.3,"finishTime":33.01},
{"lastName":"Regan-Mochrie", "firstName":"Gemma","Age":20,"Sex":"F","Pace":10.3,"finishTime":33.01},
{"lastName":"Baseggio", "firstName":"Sondra","Age":45,"Sex":"F","Pace":10.3,"finishTime":33.02},
{"lastName":"Donovan", "firstName":"Theresa","Age":60,"Sex":"F","Pace":10.3,"finishTime":33.03},
{"lastName":"Acquarulo", "firstName":"Karen","Age":44,"Sex":"F","Pace":10.3,"finishTime":33.04},
{"lastName":"Berdon", "firstName":"Nancy","Age":47,"Sex":"F","Pace":10.3,"finishTime":33.04},
{"lastName":"Morris", "firstName":"Omar","Age":45,"Sex":"M","Pace":10.4,"finishTime":33.09},
{"lastName":"Appi", "firstName":"Bonnie","Age":50,"Sex":"F","Pace":10.4,"finishTime":33.12},
{"lastName":"Ardizzone", "firstName":"Wendy","Age":49,"Sex":"F","Pace":10.4,"finishTime":33.12},
{"lastName":"Soper", "firstName":"Dylan","Age":4,"Sex":"M","Pace":10.4,"finishTime":33.13},
{"lastName":"Soper", "firstName":"Mathew","Age":38,"Sex":"M","Pace":10.4,"finishTime":33.14},
{"lastName":"Anderson", "firstName":"David","Age":51,"Sex":"M","Pace":10.4,"finishTime":33.17},
{"lastName":"Germana", "firstName":"Leslie","Age":39,"Sex":"F","Pace":10.4,"finishTime":33.18},
{"lastName":"Pierson", "firstName":"Tyler","Age":16,"Sex":"M","Pace":10.4,"finishTime":33.22},
{"lastName":"Vegliante", "firstName":"Teresa","Age":50,"Sex":"F","Pace":10.4,"finishTime":33.24},
{"lastName":"Keeney", "firstName":"Anna","Age":36,"Sex":"F","Pace":10.4,"finishTime":33.24},
{"lastName":"Theilgard", "firstName":"Maria","Age":47,"Sex":"F","Pace":10.4,"finishTime":33.24},
{"lastName":"Leigh", "firstName":"Jack","Age":13,"Sex":"M","Pace":10.4,"finishTime":33.26},
{"lastName":"Callaway", "firstName":"Bryce","Age":11,"Sex":"M","Pace":10.4,"finishTime":33.26},
{"lastName":"Signore", "firstName":"Stephanie","Age":41,"Sex":"F","Pace":10.4,"finishTime":33.27},
{"lastName":"Piazza", "firstName":"Michelle","Age":42,"Sex":"F","Pace":10.4,"finishTime":33.29},
{"lastName":"Chasse", "firstName":"Alicia","Age":47,"Sex":"F","Pace":10.4,"finishTime":33.29},
{"lastName":"Daley", "firstName":"Janet","Age":58,"Sex":"F","Pace":10.4,"finishTime":33.35},
{"lastName":"Ross", "firstName":"Katharine","Age":52,"Sex":"F","Pace":10.4,"finishTime":33.37},
{"lastName":"Depadla", "firstName":"Maria","Age":40,"Sex":"F","Pace":10.5,"finishTime":33.39},
{"lastName":"Demres", "firstName":"Gary","Age":60,"Sex":"M","Pace":10.5,"finishTime":33.4},
{"lastName":"Demeo", "firstName":"Brooke","Age":11,"Sex":"F","Pace":10.5,"finishTime":33.4},
{"lastName":"Stevens", "firstName":"Cathy","Age":51,"Sex":"F","Pace":10.5,"finishTime":33.4},
{"lastName":"MacRi", "firstName":"Kyle","Age":33,"Sex":"F","Pace":10.5,"finishTime":33.41},
{"lastName":"Weaver", "firstName":"Ethan","Age":9,"Sex":"M","Pace":10.5,"finishTime":33.42},
{"lastName":"Brainerd", "firstName":"Elijah","Age":8,"Sex":"M","Pace":10.5,"finishTime":33.47},
{"lastName":"Sachs", "firstName":"Linda","Age":54,"Sex":"F","Pace":10.5,"finishTime":33.47},
{"lastName":"Brennan", "firstName":"Kelly","Age":17,"Sex":"F","Pace":10.5,"finishTime":33.48},
{"lastName":"Govus", "firstName":"Alex","Age":17,"Sex":"M","Pace":10.5,"finishTime":33.52},
{"lastName":"Geballe", "firstName":"Kaylee","Age":7,"Sex":"F","Pace":10.5,"finishTime":33.54},
{"lastName":"Geballe", "firstName":"Josh","Age":39,"Sex":"M","Pace":10.5,"finishTime":33.56},
{"lastName":"Piacentini", "firstName":"Laura","Age":51,"Sex":"F","Pace":10.5,"finishTime":34.03},
{"lastName":"Ross", "firstName":"Andrea","Age":50,"Sex":"F","Pace":10.5,"finishTime":34.03},
{"lastName":"Sparks", "firstName":"Melissa","Age":27,"Sex":"F","Pace":10.5,"finishTime":34.04},
{"lastName":"Ringer", "firstName":"Lauren","Age":24,"Sex":"F","Pace":10.5,"finishTime":34.07},
{"lastName":"McKee", "firstName":"Ross","Age":8,"Sex":"M","Pace":10.5,"finishTime":34.08},
{"lastName":"Stoll", "firstName":"Steven","Age":48,"Sex":"M","Pace":11.0,"finishTime":34.13},
{"lastName":"Bogart", "firstName":"Nelson","Age":64,"Sex":"M","Pace":11.0,"finishTime":34.14},
{"lastName":"Rizzuto", "firstName":"Michelle","Age":31,"Sex":"F","Pace":11.0,"finishTime":34.14},
{"lastName":"McKee", "firstName":"Jake","Age":10,"Sex":"F","Pace":11.0,"finishTime":34.15},
{"lastName":"McKee", "firstName":"Mary","Age":44,"Sex":"F","Pace":11.0,"finishTime":34.15},
{"lastName":"Revenaugh", "firstName":"Beau","Age":8,"Sex":"M","Pace":11.0,"finishTime":34.16},
{"lastName":"Benzi", "firstName":"Fiona","Age":14,"Sex":"F","Pace":11.0,"finishTime":34.2},
{"lastName":"Skovron", "firstName":"Jennifer","Age":37,"Sex":"F","Pace":11.0,"finishTime":34.21},
{"lastName":"Halsema", "firstName":"Elise","Age":9,"Sex":"F","Pace":11.0,"finishTime":34.22},
{"lastName":"McCarthy", "firstName":"Sean","Age":9,"Sex":"M","Pace":11.0,"finishTime":34.22},
{"lastName":"Vescera", "firstName":"Tyler","Age":9,"Sex":"M","Pace":11.0,"finishTime":34.22},
{"lastName":"Weaver", "firstName":"Dylan","Age":6,"Sex":"M","Pace":11.0,"finishTime":34.23},
{"lastName":"Dangora", "firstName":"Jennifer","Age":30,"Sex":"F","Pace":11.0,"finishTime":34.23},
{"lastName":"Keeney", "firstName":"Sean","Age":36,"Sex":"M","Pace":11.0,"finishTime":34.25},
{"lastName":"Brooks", "firstName":"Harper","Age":7,"Sex":"F","Pace":11.0,"finishTime":34.26},
{"lastName":"Brooks", "firstName":"Andrew","Age":39,"Sex":"M","Pace":11.0,"finishTime":34.27},
{"lastName":"Regan", "firstName":"Lynne","Age":55,"Sex":"F","Pace":11.0,"finishTime":34.27},
{"lastName":"Duntz", "firstName":"Brittney","Age":26,"Sex":"F","Pace":11.0,"finishTime":34.28},
{"lastName":"Maercklein", "firstName":"Linda","Age":49,"Sex":"F","Pace":11.0,"finishTime":34.28},
{"lastName":"Alderman", "firstName":"Stephanie","Age":34,"Sex":"F","Pace":11.0,"finishTime":34.29},
{"lastName":"Powell", "firstName":"Leslie","Age":46,"Sex":"F","Pace":11.0,"finishTime":34.31},
{"lastName":"Jacobson", "firstName":"Karl","Age":44,"Sex":"M","Pace":11.0,"finishTime":34.32},
{"lastName":"Brainerd", "firstName":"Andrew","Age":8,"Sex":"M","Pace":11.0,"finishTime":34.33},
{"lastName":"Brainerd", "firstName":"Marcie","Age":38,"Sex":"F","Pace":11.0,"finishTime":34.33},
{"lastName":"D'Onofrio", "firstName":"Madison","Age":16,"Sex":"F","Pace":11.0,"finishTime":34.34},
{"lastName":"Riggs", "firstName":"Foley","Age":16,"Sex":"F","Pace":11.0,"finishTime":34.35},
{"lastName":"Welch", "firstName":"Matthew","Age":37,"Sex":"M","Pace":11.0,"finishTime":34.37},
{"lastName":"Stegina", "firstName":"Gary","Age":59,"Sex":"M","Pace":11.1,"finishTime":34.4},
{"lastName":"Aghajanian", "firstName":"Madeline","Age":16,"Sex":"F","Pace":11.1,"finishTime":34.44},
{"lastName":"Jacobson", "firstName":"Dawnown","Age":48,"Sex":"F","Pace":11.1,"finishTime":34.48},
{"lastName":"Page", "firstName":"Heather","Age":38,"Sex":"F","Pace":11.1,"finishTime":34.48},
{"lastName":"Page", "firstName":"Theresa","Age":62,"Sex":"F","Pace":11.1,"finishTime":34.49},
{"lastName":"Kiely", "firstName":"Caroline","Age":41,"Sex":"F","Pace":11.1,"finishTime":34.53},
{"lastName":"Harper", "firstName":"Theresa","Age":52,"Sex":"F","Pace":11.1,"finishTime":34.54},
{"lastName":"Dwyer", "firstName":"Cindy","Age":44,"Sex":"F","Pace":11.1,"finishTime":34.57},
{"lastName":"Jackson", "firstName":"Kent","Age":48,"Sex":"M","Pace":11.1,"finishTime":35},
{"lastName":"Weaver", "firstName":"Jodi","Age":41,"Sex":"F","Pace":11.1,"finishTime":35.04},
{"lastName":"Moore", "firstName":"Mason","Age":11,"Sex":"M","Pace":11.1,"finishTime":35.09},
{"lastName":"Gage", "firstName":"Amanda","Age":12,"Sex":"F","Pace":11.1,"finishTime":35.09},
{"lastName":"Rhone", "firstName":"Shannon","Age":13,"Sex":"F","Pace":11.1,"finishTime":35.1},
{"lastName":"Copenhaver", "firstName":"Emily","Age":13,"Sex":"F","Pace":11.1,"finishTime":35.1},
{"lastName":"Wright", "firstName":"Rebecca","Age":26,"Sex":"F","Pace":11.2,"finishTime":35.13},
{"lastName":"Harris", "firstName":"John","Age":30,"Sex":"M","Pace":11.2,"finishTime":35.13},
{"lastName":"Rubsam", "firstName":"Chelsea","Age":21,"Sex":"F","Pace":11.2,"finishTime":35.14},
{"lastName":"Kaplan", "firstName":"Michael","Age":21,"Sex":"M","Pace":11.2,"finishTime":35.15},
{"lastName":"Ringer", "firstName":"Kathryn","Age":26,"Sex":"F","Pace":11.2,"finishTime":35.22},
{"lastName":"Howlett", "firstName":"Nick","Age":11,"Sex":"M","Pace":11.2,"finishTime":35.24},
{"lastName":"Demeo", "firstName":"Dawn","Age":41,"Sex":"F","Pace":11.2,"finishTime":35.28},
{"lastName":"Bronner", "firstName":"Hailey","Age":12,"Sex":"F","Pace":11.2,"finishTime":35.29},
{"lastName":"Hanson", "firstName":"Mae","Age":18,"Sex":"F","Pace":11.2,"finishTime":35.29},
{"lastName":"Gage", "firstName":"Elizabeth","Age":49,"Sex":"F","Pace":11.2,"finishTime":35.32},
{"lastName":"Kramer", "firstName":"Audrey","Age":56,"Sex":"F","Pace":11.2,"finishTime":35.34},
{"lastName":"Baker", "firstName":"Darbi","Age":30,"Sex":"F","Pace":11.2,"finishTime":35.34},
{"lastName":"Foley", "firstName":"Danine","Age":39,"Sex":"F","Pace":11.2,"finishTime":35.38},
{"lastName":"McCarroll", "firstName":"Mason","Age":8,"Sex":"M","Pace":11.2,"finishTime":35.41},
{"lastName":"Jones", "firstName":"Zachary","Age":11,"Sex":"M","Pace":11.3,"finishTime":35.41},
{"lastName":"Jones", "firstName":"Christine","Age":42,"Sex":"F","Pace":11.3,"finishTime":35.41},
{"lastName":"Noecker", "firstName":"Bianca","Age":8,"Sex":"F","Pace":11.3,"finishTime":35.42},
{"lastName":"Noecker", "firstName":"Robert","Age":50,"Sex":"M","Pace":11.3,"finishTime":35.42},
{"lastName":"Callaway", "firstName":"Greg","Age":44,"Sex":"M","Pace":11.3,"finishTime":35.42},
{"lastName":"Callaway", "firstName":"Skyler","Age":8,"Sex":"F","Pace":11.3,"finishTime":35.43},
{"lastName":"Salzano", "firstName":"Erin","Age":36,"Sex":"F","Pace":11.3,"finishTime":35.43},
{"lastName":"McCarroll", "firstName":"Alora","Age":11,"Sex":"F","Pace":11.3,"finishTime":35.44},
{"lastName":"Salzano", "firstName":"Gina","Age":38,"Sex":"F","Pace":11.3,"finishTime":35.44},
{"lastName":"McCarroll", "firstName":"Nikky","Age":38,"Sex":"F","Pace":11.3,"finishTime":35.44},
{"lastName":"Greenhouse", "firstName":"Madelyn","Age":13,"Sex":"F","Pace":11.3,"finishTime":35.45},
{"lastName":"Demaio", "firstName":"Donna","Age":55,"Sex":"F","Pace":11.3,"finishTime":35.45},
{"lastName":"Pierson", "firstName":"Halley","Age":9,"Sex":"F","Pace":11.3,"finishTime":35.46},
{"lastName":"Frost", "firstName":"Ava","Age":12,"Sex":"F","Pace":11.3,"finishTime":35.51},
{"lastName":"Maymon", "firstName":"Sloane","Age":39,"Sex":"F","Pace":11.3,"finishTime":35.53},
{"lastName":"Maymon", "firstName":"Jim","Age":41,"Sex":"M","Pace":11.3,"finishTime":35.53},
{"lastName":"Maymon", "firstName":"Casey","Age":10,"Sex":"M","Pace":11.3,"finishTime":35.53},
{"lastName":"Demeo", "firstName":"Deborah","Age":40,"Sex":"F","Pace":11.3,"finishTime":35.53},
{"lastName":"Small", "firstName":"Jason","Age":39,"Sex":"M","Pace":11.3,"finishTime":35.54},
{"lastName":"O'Neil", "firstName":"Olivia","Age":11,"Sex":"F","Pace":11.3,"finishTime":35.55},
{"lastName":"Digiulian", "firstName":"Giovanni","Age":9,"Sex":"M","Pace":11.3,"finishTime":36},
{"lastName":"Babcock", "firstName":"Andrea","Age":32,"Sex":"F","Pace":11.3,"finishTime":36.03},
{"lastName":"Edmonds", "firstName":"Meagan","Age":22,"Sex":"F","Pace":11.3,"finishTime":36.05},
{"lastName":"Digiulian", "firstName":"Damian","Age":44,"Sex":"M","Pace":11.3,"finishTime":36.07},
{"lastName":"Russell", "firstName":"Joanne","Age":53,"Sex":"F","Pace":11.3,"finishTime":36.09},
{"lastName":"Edmonds", "firstName":"Christian","Age":61,"Sex":"M","Pace":11.3,"finishTime":36.1},
{"lastName":"Child", "firstName":"Patty","Age":50,"Sex":"F","Pace":11.4,"finishTime":36.25},
{"lastName":"Iuliano", "firstName":"Raffaele","Age":25,"Sex":"M","Pace":11.4,"finishTime":36.27},
{"lastName":"Standish", "firstName":"Kate","Age":33,"Sex":"F","Pace":11.4,"finishTime":36.28},
{"lastName":"Stak", "firstName":"Greg","Age":55,"Sex":"M","Pace":11.4,"finishTime":36.29},
{"lastName":"Sachs", "firstName":"Sarah","Age":22,"Sex":"F","Pace":11.4,"finishTime":36.31},
{"lastName":"Pombo", "firstName":"Alexandra","Age":11,"Sex":"F","Pace":11.4,"finishTime":36.37},
{"lastName":"Beers", "firstName":"John","Age":60,"Sex":"M","Pace":11.4,"finishTime":36.42},
{"lastName":"Frankes", "firstName":"Lisa","Age":56,"Sex":"F","Pace":11.5,"finishTime":36.5},
{"lastName":"Webb", "firstName":"Julia","Age":36,"Sex":"F","Pace":11.5,"finishTime":36.51},
{"lastName":"Webb", "firstName":"Clara","Age":32,"Sex":"F","Pace":11.5,"finishTime":36.51},
{"lastName":"Marks", "firstName":"Charles","Age":48,"Sex":"M","Pace":11.5,"finishTime":36.51},
{"lastName":"Alberino", "firstName":"Rebecca","Age":37,"Sex":"F","Pace":11.5,"finishTime":36.55},
{"lastName":"Lupo", "firstName":"Amy","Age":41,"Sex":"F","Pace":11.5,"finishTime":37.03},
{"lastName":"Augkatavianich", "firstName":"Todd","Age":47,"Sex":"M","Pace":11.5,"finishTime":37.08},
{"lastName":"Roth", "firstName":"Danielle","Age":15,"Sex":"F","Pace":11.5,"finishTime":37.11},
{"lastName":"McCarroll", "firstName":"Ryan","Age":39,"Sex":"M","Pace":11.5,"finishTime":37.11},
{"lastName":"Brennan", "firstName":"Edward","Age":50,"Sex":"M","Pace":12.0,"finishTime":37.23},
{"lastName":"Sutcliffe", "firstName":"Susan","Age":51,"Sex":"F","Pace":12.0,"finishTime":37.3},
{"lastName":"Mariotti", "firstName":"Siena","Age":21,"Sex":"F","Pace":12.0,"finishTime":37.33},
{"lastName":"Walden", "firstName":"Emily","Age":28,"Sex":"F","Pace":12.0,"finishTime":37.34},
{"lastName":"Walden", "firstName":"Margaret","Age":58,"Sex":"F","Pace":12.0,"finishTime":37.35},
{"lastName":"Fraser", "firstName":"Debbie","Age":58,"Sex":"F","Pace":12.0,"finishTime":37.36},
{"lastName":"Anderon", "firstName":"Hannah","Age":24,"Sex":"F","Pace":12.0,"finishTime":37.39},
{"lastName":"Phim", "firstName":"Bunlin","Age":34,"Sex":"F","Pace":12.0,"finishTime":37.44},
{"lastName":"Johnson", "firstName":"Pete","Age":61,"Sex":"M","Pace":12.1,"finishTime":37.49},
{"lastName":"Sutcliffe", "firstName":"Richard","Age":51,"Sex":"M","Pace":12.1,"finishTime":37.5},
{"lastName":"Haile", "firstName":"Ian","Age":11,"Sex":"M","Pace":12.1,"finishTime":38.01},
{"lastName":"Keller", "firstName":"Lani","Age":35,"Sex":"F","Pace":12.1,"finishTime":38.09},
{"lastName":"Hernandez", "firstName":"Hamlet","Age":52,"Sex":"M","Pace":12.1,"finishTime":38.1},
{"lastName":"Lecza", "firstName":"Kim","Age":45,"Sex":"F","Pace":12.1,"finishTime":38.1},
{"lastName":"Stak", "firstName":"Bernadette","Age":55,"Sex":"F","Pace":12.1,"finishTime":38.13},
{"lastName":"Demeo", "firstName":"Molly","Age":11,"Sex":"F","Pace":12.1,"finishTime":38.14},
{"lastName":"Larsen", "firstName":"Jean","Age":63,"Sex":"F","Pace":12.2,"finishTime":38.17},
{"lastName":"Romberg", "firstName":"Betty","Age":65,"Sex":"F","Pace":12.2,"finishTime":38.18},
{"lastName":"Romberg", "firstName":"Wayne","Age":68,"Sex":"M","Pace":12.2,"finishTime":38.19},
{"lastName":"Copenhaver", "firstName":"Charlotte","Age":52,"Sex":"F","Pace":12.2,"finishTime":38.2},
{"lastName":"Pascarella", "firstName":"Ava","Age":9,"Sex":"F","Pace":12.2,"finishTime":38.23},
{"lastName":"Lux", "firstName":"Madeleine","Age":27,"Sex":"F","Pace":12.2,"finishTime":38.3},
{"lastName":"Ajgkatavanice", "firstName":"Ann","Age":13,"Sex":"F","Pace":12.2,"finishTime":38.39},
{"lastName":"Ametrano", "firstName":"Lucas","Age":8,"Sex":"M","Pace":12.2,"finishTime":38.4},
{"lastName":"Ametrano", "firstName":"Joe","Age":45,"Sex":"M","Pace":12.2,"finishTime":38.42},
{"lastName":"Pascarella", "firstName":"Michelle","Age":43,"Sex":"F","Pace":12.3,"finishTime":38.52},
{"lastName":"Pascarella", "firstName":"Carmen","Age":43,"Sex":"M","Pace":12.3,"finishTime":39.12},
{"lastName":"Kuehl", "firstName":"Jacqueline","Age":46,"Sex":"F","Pace":12.3,"finishTime":39.13},
{"lastName":"Cochran", "firstName":"Michelle","Age":32,"Sex":"F","Pace":12.4,"finishTime":39.22},
{"lastName":"Callaway", "firstName":"Wayne","Age":78,"Sex":"M","Pace":12.4,"finishTime":39.25},
{"lastName":"Moore", "firstName":"Justine","Age":40,"Sex":"F","Pace":12.4,"finishTime":39.31},
{"lastName":"Cronin", "firstName":"Cheryl","Age":48,"Sex":"F","Pace":12.4,"finishTime":39.4},
{"lastName":"Ing", "firstName":"Katherine","Age":61,"Sex":"F","Pace":12.4,"finishTime":39.4},
{"lastName":"Reid", "firstName":"Matthew","Age":31,"Sex":"M","Pace":12.5,"finishTime":39.55},
{"lastName":"Walker", "firstName":"Breset","Age":34,"Sex":"F","Pace":12.5,"finishTime":39.55},
{"lastName":"Woodward", "firstName":"Keith","Age":49,"Sex":"M","Pace":12.5,"finishTime":40.05},
{"lastName":"Chasse", "firstName":"Adam","Age":10,"Sex":"M","Pace":12.5,"finishTime":40.05},
{"lastName":"Acosta", "firstName":"Nichole","Age":27,"Sex":"F","Pace":12.5,"finishTime":40.07},
{"lastName":"Pimentel", "firstName":"Robert","Age":56,"Sex":"M","Pace":13.0,"finishTime":40.27},
{"lastName":"Pombo", "firstName":"Jake","Age":6,"Sex":"M","Pace":13.1,"finishTime":40.52},
{"lastName":"Leeper", "firstName":"Karen","Age":58,"Sex":"F","Pace":13.1,"finishTime":41.01},
{"lastName":"Tornquist", "firstName":"Elizabeth","Age":42,"Sex":"F","Pace":13.3,"finishTime":42.03},
{"lastName":"Howlett", "firstName":"Jennifer","Age":40,"Sex":"F","Pace":13.3,"finishTime":42.2},
{"lastName":"Braun", "firstName":"Laura","Age":56,"Sex":"F","Pace":13.4,"finishTime":42.44},
{"lastName":"Braun", "firstName":"George","Age":67,"Sex":"M","Pace":13.4,"finishTime":42.44},
{"lastName":"Skovron", "firstName":"Steven","Age":39,"Sex":"M","Pace":13.4,"finishTime":42.44},
{"lastName":"Coagnon", "firstName":"Melissa","Age":28,"Sex":"F","Pace":13.4,"finishTime":42.54},
{"lastName":"Lee", "firstName":"Anna-Maria","Age":40,"Sex":"F","Pace":13.5,"finishTime":43},
{"lastName":"Small", "firstName":"Noelle","Age":8,"Sex":"F","Pace":13.5,"finishTime":43},
{"lastName":"Hebermehl", "firstName":"Wanda","Age":47,"Sex":"F","Pace":13.5,"finishTime":43.08},
{"lastName":"Petrakis", "firstName":"Ismene","Age":53,"Sex":"F","Pace":13.5,"finishTime":43.09},
{"lastName":"Sernyak", "firstName":"Zoe","Age":16,"Sex":"F","Pace":13.5,"finishTime":43.09},
{"lastName":"Ortiz", "firstName":"Jennifer","Age":31,"Sex":"F","Pace":13.5,"finishTime":43.23},
{"lastName":"Ehrhardt", "firstName":"Maria","Age":45,"Sex":"F","Pace":13.5,"finishTime":43.23},
{"lastName":"Coleman", "firstName":"Margaret","Age":36,"Sex":"F","Pace":13.5,"finishTime":43.25},
{"lastName":"Connelly", "firstName":"Karen","Age":33,"Sex":"F","Pace":13.5,"finishTime":43.25},
{"lastName":"Ochman", "firstName":"Priscilla","Age":61,"Sex":"F","Pace":14.0,"finishTime":43.28},
{"lastName":"Ochman", "firstName":"Chelsea","Age":30,"Sex":"F","Pace":14.0,"finishTime":43.28},
{"lastName":"Kelsey", "firstName":"Chandra","Age":34,"Sex":"F","Pace":14.0,"finishTime":43.28},
{"lastName":"Dole", "firstName":"Emma","Age":8,"Sex":"F","Pace":14.0,"finishTime":43.35},
{"lastName":"Young", "firstName":"Kristin","Age":39,"Sex":"F","Pace":14.0,"finishTime":43.35},
{"lastName":"Bennett", "firstName":"Alec","Age":35,"Sex":"M","Pace":14.0,"finishTime":43.36},
{"lastName":"Rauccio", "firstName":"Alex","Age":12,"Sex":"M","Pace":14.0,"finishTime":43.39},
{"lastName":"Brooks", "firstName":"Sherry","Age":70,"Sex":"F","Pace":14.0,"finishTime":43.44},
{"lastName":"Gage", "firstName":"Kathleen","Age":70,"Sex":"F","Pace":14.0,"finishTime":43.53},
{"lastName":"Johnson", "firstName":"Rhonda","Age":43,"Sex":"F","Pace":14.1,"finishTime":44.06},
{"lastName":"Tucker", "firstName":"Valerie","Age":57,"Sex":"F","Pace":14.1,"finishTime":44.27},
{"lastName":"Obrien", "firstName":"Jennifer","Age":38,"Sex":"F","Pace":14.2,"finishTime":44.35},
{"lastName":"Curtis", "firstName":"Frances","Age":65,"Sex":"F","Pace":14.3,"finishTime":45.03},
{"lastName":"Litt", "firstName":"Ellen","Age":67,"Sex":"F","Pace":14.3,"finishTime":45.13},
{"lastName":"Marks", "firstName":"Ellen","Age":76,"Sex":"F","Pace":14.3,"finishTime":45.15},
{"lastName":"Marks", "firstName":"Anthony","Age":77,"Sex":"M","Pace":14.3,"finishTime":45.15},
{"lastName":"McMahon", "firstName":"Erin","Age":46,"Sex":"F","Pace":14.3,"finishTime":45.19},
{"lastName":"D'Onofrio", "firstName":"Ethan","Age":9,"Sex":"M","Pace":14.3,"finishTime":45.2},
{"lastName":"Digiulian", "firstName":"Kelly","Age":43,"Sex":"F","Pace":14.4,"finishTime":45.34},
{"lastName":"Wright", "firstName":"Philip","Age":29,"Sex":"M","Pace":14.4,"finishTime":45.34},
{"lastName":"Mohan", "firstName":"Emily","Age":22,"Sex":"F","Pace":14.4,"finishTime":45.36},
{"lastName":"Gordon", "firstName":"Tamara","Age":34,"Sex":"F","Pace":14.4,"finishTime":45.39},
{"lastName":"Fritz", "firstName":"Jessica","Age":28,"Sex":"F","Pace":14.4,"finishTime":45.45},
{"lastName":"Davis", "firstName":"Kelly","Age":42,"Sex":"F","Pace":14.4,"finishTime":45.49},
{"lastName":"Meagher", "firstName":"John","Age":65,"Sex":"M","Pace":14.4,"finishTime":45.51},
{"lastName":"Digiulian", "firstName":"Bernadette","Age":75,"Sex":"F","Pace":14.5,"finishTime":46.19},
{"lastName":"Cristofar", "firstName":"Leo","Age":71,"Sex":"M","Pace":14.5,"finishTime":46.19},
{"lastName":"Moore", "firstName":"Carter","Age":8,"Sex":"M","Pace":14.5,"finishTime":46.24},
{"lastName":"Moore", "firstName":"Chris","Age":44,"Sex":"M","Pace":14.5,"finishTime":46.32},
{"lastName":"Crowell", "firstName":"Brad","Age":60,"Sex":"M","Pace":15.0,"finishTime":46.51},
{"lastName":"Nilsson", "firstName":"Shona","Age":31,"Sex":"F","Pace":15.1,"finishTime":47.06},
{"lastName":"Hebermehl", "firstName":"Nicole","Age":26,"Sex":"F","Pace":15.1,"finishTime":47.16},
{"lastName":"Corbett", "firstName":"Emma","Age":19,"Sex":"F","Pace":15.2,"finishTime":47.53},
{"lastName":"Mishler", "firstName":"Elizabeth","Age":55,"Sex":"F","Pace":15.2,"finishTime":47.53},
{"lastName":"Pierson", "firstName":"Russ","Age":46,"Sex":"M","Pace":15.2,"finishTime":47.54},
{"lastName":"Lecza", "firstName":"Susan","Age":48,"Sex":"F","Pace":15.2,"finishTime":47.59},
{"lastName":"Edmonds", "firstName":"Marisa","Age":24,"Sex":"F","Pace":15.2,"finishTime":48.06},
{"lastName":"Amendola", "firstName":"Lauren","Age":31,"Sex":"F","Pace":15.3,"finishTime":48.09},
{"lastName":"Dilella", "firstName":"Dave","Age":55,"Sex":"M","Pace":15.3,"finishTime":48.11},
{"lastName":"Amendola", "firstName":"Stephanie","Age":33,"Sex":"F","Pace":15.3,"finishTime":48.11},
{"lastName":"Frost", "firstName":"Jennifer","Age":42,"Sex":"F","Pace":15.3,"finishTime":48.33},
{"lastName":"Huzar", "firstName":"Edith","Age":65,"Sex":"F","Pace":15.3,"finishTime":48.33},
{"lastName":"Stevenson", "firstName":"David","Age":57,"Sex":"M","Pace":15.4,"finishTime":48.54},
{"lastName":"Stevenson", "firstName":"Maura","Age":57,"Sex":"F","Pace":15.4,"finishTime":48.55},
{"lastName":"Degoursey", "firstName":"Ruby","Age":9,"Sex":"F","Pace":15.5,"finishTime":49.16},
{"lastName":"Degoursey", "firstName":"Robert","Age":43,"Sex":"M","Pace":15.5,"finishTime":49.16},
{"lastName":"Shay", "firstName":"Alex","Age":21,"Sex":"F","Pace":15.5,"finishTime":49.19},
{"lastName":"Degoursey", "firstName":"Kaley","Age":40,"Sex":"F","Pace":15.5,"finishTime":49.2},
{"lastName":"Roth", "firstName":"Dan","Age":50,"Sex":"M","Pace":16.0,"finishTime":50.01},
{"lastName":"Won", "firstName":"Christine","Age":40,"Sex":"F","Pace":16.1,"finishTime":50.11},
{"lastName":"Fedorchak", "firstName":"Hallie","Age":13,"Sex":"F","Pace":16.1,"finishTime":50.34},
{"lastName":"Tornquist", "firstName":"Catherine","Age":8,"Sex":"F","Pace":16.1,"finishTime":50.34},
{"lastName":"Tornquist", "firstName":"Jon","Age":41,"Sex":"M","Pace":16.1,"finishTime":50.34},
{"lastName":"Marks", "firstName":"Jennifer","Age":53,"Sex":"F","Pace":16.2,"finishTime":50.44},
{"lastName":"Ricciardelli", "firstName":"Jessica","Age":47,"Sex":"F","Pace":16.2,"finishTime":50.44},
{"lastName":"Soper", "firstName":"Cailey","Age":11,"Sex":"F","Pace":16.2,"finishTime":50.46},
{"lastName":"Soper", "firstName":"Carolyne","Age":36,"Sex":"F","Pace":16.2,"finishTime":51.06},
{"lastName":"Russell", "firstName":"Hannah","Age":14,"Sex":"F","Pace":16.3,"finishTime":51.17},
{"lastName":"Perry", "firstName":"Audreyn","Age":11,"Sex":"F","Pace":16.3,"finishTime":51.17},
{"lastName":"Pierson", "firstName":"Fran","Age":48,"Sex":"F","Pace":16.3,"finishTime":51.31},
{"lastName":"Pierson", "firstName":"Carolyn","Age":72,"Sex":"F","Pace":16.3,"finishTime":51.32},
{"lastName":"Jones", "firstName":"Jennifer","Age":50,"Sex":"F","Pace":16.3,"finishTime":51.33},
{"lastName":"Pajamo", "firstName":"Sam","Age":66,"Sex":"M","Pace":16.5,"finishTime":52.17},
{"lastName":"McNamara", "firstName":"Susan","Age":58,"Sex":"F","Pace":16.5,"finishTime":52.28},
{"lastName":"Anderson", "firstName":"Elizabeth","Age":52,"Sex":"F","Pace":17.0,"finishTime":52.51},
{"lastName":"Anderson", "firstName":"Karl","Age":52,"Sex":"M","Pace":17.0,"finishTime":52.51},
{"lastName":"Sernyak", "firstName":"Pat","Age":77,"Sex":"F","Pace":17.1,"finishTime":53.26},
{"lastName":"Hernandez", "firstName":"Rachel","Age":20,"Sex":"F","Pace":17.2,"finishTime":53.58},
{"lastName":"Hernandez", "firstName":"Sara","Age":52,"Sex":"F","Pace":17.2,"finishTime":53.58},
{"lastName":"Dole", "firstName":"Christopher","Age":10,"Sex":"M","Pace":17.3,"finishTime":54.2},
{"lastName":"Young", "firstName":"Elizabeth","Age":41,"Sex":"F","Pace":17.3,"finishTime":54.2},
{"lastName":"Demusis", "firstName":"Deborah","Age":59,"Sex":"F","Pace":17.3,"finishTime":54.21},
{"lastName":"Callaway", "firstName":"Peggy","Age":74,"Sex":"F","Pace":17.3,"finishTime":54.36},
{"lastName":"Bohan", "firstName":"James","Age":72,"Sex":"M","Pace":17.3,"finishTime":54.47},
{"lastName":"Cohn", "firstName":"Susan","Age":36,"Sex":"F","Pace":17.4,"finishTime":55.02},
{"lastName":"Ayr", "firstName":"Lauren","Age":36,"Sex":"F","Pace":17.4,"finishTime":55.02},
{"lastName":"Horsford", "firstName":"Jesse","Age":35,"Sex":"M","Pace":17.4,"finishTime":55.04},
{"lastName":"Horsford", "firstName":"Carol","Age":37,"Sex":"F","Pace":17.4,"finishTime":55.04},
{"lastName":"Salzano", "firstName":"Ava","Age":6,"Sex":"F","Pace":17.4,"finishTime":55.13},
{"lastName":"Salzano", "firstName":"Barbara","Age":52,"Sex":"F","Pace":17.5,"finishTime":55.27},
{"lastName":"Kelly", "firstName":"Kathleen","Age":53,"Sex":"F","Pace":17.5,"finishTime":55.28},
{"lastName":"Salzano", "firstName":"Richard","Age":52,"Sex":"M","Pace":17.5,"finishTime":55.29},
{"lastName":"Visnic", "firstName":"Molly","Age":48,"Sex":"F","Pace":17.5,"finishTime":55.39},
{"lastName":"Santoro", "firstName":"Patricia","Age":57,"Sex":"F","Pace":18.0,"finishTime":56.18},
{"lastName":"Ocame", "firstName":"David","Age":53,"Sex":"M","Pace":18.0,"finishTime":56.18},
{"lastName":"Osbourne", "firstName":"Donald","Age":93,"Sex":"M","Pace":19.3,"finishTime":60.04},
{"lastName":"Lyons", "firstName":"Lauretta","Age":49,"Sex":"F","Pace":19.4,"finishTime":61.01},
{"lastName":"Lyons", "firstName":"Madeline","Age":81,"Sex":"F","Pace":19.4,"finishTime":61.24},
{"lastName":"O'Brien", "firstName":"Jane","Age":70,"Sex":"F","Pace":20.2,"finishTime":63.45}];


// var data = [{
// 	name: "Judy",
// 	finishTime: 50
// },
// {
// 	name: "Mike",
// 	finishTime: 90
// },
// {
// 	name: "Mochi",
// 	finishTime: 100
// },
// {
// 	name: "Furby",
// 	finishTime: 30
// }
// ];


var data2= [1, 2, 3];
var width = 1000;
var height = 600;
var padding = 100;


// function make_x_axis() {        
//     return d3.svg.axis()
//         .scale(x)
//          .orient("bottom")
//          .ticks(5)
// }


 var renderData = function(){
var svg = d3.select('body').append('svg')
	.attr('width', width)
	.attr('height', height)




	 var runner = svg.selectAll('rect')
	    .data(data); 

	 console.log(runner);

	 var genderData = function(gender){
      	// console.log(gender.sex);
      	if(gender.Sex === "F"){
      		return "pink";
      	}
      	// console.log('it got here')
      	return "blue";
	 };


	 runner.enter()
      .append('circle')
      .attr('class', 'runner')
      .attr('width', 12)
      .attr('height', 12)
      .attr('r', 5)
      .attr('cx', function(px){ console.log('px', px);
      	return (px.finishTime*width - padding)/60;})
      .attr('cy', function(py){ if(py.Sex === 'F'){
      	return 50-(Math.random()*50);} return 100+(Math.random()*50);})
      .attr('width', 12)
      .attr('height', 12)
      .attr('fill', genderData)
      .on("mouseover", function(d) {
		d3.select(this).attr("fill", "orange");

		var xPosition = parseFloat(d3.select(this).attr("cx"));
		var yPosition = parseFloat(d3.select(this).attr("cy"));

		d3.select("#tooltip")
		  .style("left", xPosition + "px")
		  .style("top", yPosition + "px")
		  .select("#value")
		  .text(
		  	"\nFirst Name:" + d.firstName +
		  	"\n\nLast Name:" + d.lastName + 
		  	"\nAge:" + d.Age +
		  	"\nSex:" + d.Sex + 
		  	"\n\nFinishTime:" + d.finishTime)


		//Show the tooltip
		d3.select("#tooltip").classed("hidden", false);

	})
      .on("mouseout", function(){
		d3.select(this)
			.attr('fill', genderData);
		d3.select("#tooltip").classed("hidden", true);
	})







      .transition();
    // var letters = '0123456789ABCDEF'.split('');
    // var color = '#';
    // for (var i = 0; i < 6; i++ ) {
    //     color += letters[Math.floor(Math.random() * 16)];
    // }
    // return color;
     runner.exit().remove();


     var scale = d3.scale.linear()
                    .domain([0, 120])
                    .range([0, 1000]);


     var xScale = d3.scale.linear()
                     .domain([0, d3.max(data, function(d) { return d.finishTime; })])
                     .range([0, width]);
     var xAxis = d3.svg.axis()
                  .scale(xScale)

                  .orient("bottom");

     svg.append("g")
      .attr("transform", "translate(0," + (75) + ")")
    .call(xAxis);



};

$(document).ready(function(){

renderData();
})
